# Get ubuntu image with python 3.12 already installed
FROM python:3.12.3-bullseye

# Set working directory
WORKDIR /app

# Copy over enough to build the development virtual environment.
COPY requirements.dev.txt .
COPY pyproject.toml .
COPY Makefile .

# Build the development virtual environment.
RUN make venv-dev
