# Get ubuntu image with python 3.12 already installed
FROM ghcr.io/zengenti/flask-forge:latest

# Set working directory
RUN mkdir -p /usr/src/
WORKDIR /usr/src
COPY requirements.dev.txt .
COPY pyproject.toml .
COPY Makefile .

# Copy over enough to build the development virtual environment.
COPY requirements.dev.txt .
COPY pyproject.toml .
COPY Makefile .

# Build the development virtual environment.
RUN make venv-dev
