name: Build Docker image and push to Dockerhub

on:
  push:
    branches: [ main ]

# Run building the docker image that runs our Flask App?
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo.
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Production Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          zengenti/flask-forge:latest
          zengenti/flask-forge:${GITHUB_SHA::6}

    # - name: Build and Push Development Docker Image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./Dockerfile.dev
    #     push: true
    #     tags: |
    #       zengenti/flask-forge-dev:latest
