---
name: Run the Python Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zengenti/flask-forge:latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Symlink to virtual environment in container image
        run: |
          ln -s .venv/bin/python /app/.venv/bin/python
      - name: Run tests.
        env:
          SOURCERY_TOKEN: ${{ secrets.SOURCERY_TOKEN }}
        run: |
          make report
          make lint
          make test
