---
name: Run the Python Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Create the virtual environment and run tests.
        env:
          SOURCERY_TOKEN: ${{ secrets.SOURCERY_TOKEN }}
        run: |
          make venv
          make report
          printenv
          make lint

          make test
