---
name: Run the Python Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: self-hosted
    container:
      image: ghcr.io/zengenti/flask-forge-dev:latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Create the virtual environment and run tests.
        env:
          SOURCERY_TOKEN: ${{ secrets.SOURCERY_TOKEN }}
        run: |
          make venv-dev
          make report
          make lint
          make test
